/*
 Navicat Premium Data Transfer

 Source Server         : harnicproducts.com
 Source Server Type    : MySQL
 Source Server Version : 50644
 Source Host           : harnicproducts.com:3306
 Source Schema         : hervee

 Target Server Type    : MySQL
 Target Server Version : 50644
 File Encoding         : 65001

 Date: 19/09/2019 11:10:23
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO `countries`(id, isocode, name, phonecode) VALUES (1, 'ID', 'Indonesia', '62');

-- ----------------------------
-- Table structure for provinces
-- ----------------------------
-- DROP TABLE IF EXISTS `provinces`;
-- CREATE TABLE `provinces`  (
--   `prov_id` int(11) NOT NULL AUTO_INCREMENT,
--   `prov_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
--   `locationid` int(11) NULL DEFAULT NULL,
--   `status` int(11) NULL DEFAULT 1,
--   PRIMARY KEY (`prov_id`) USING BTREE
-- ) ENGINE = MyISAM AUTO_INCREMENT = 35 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of provinces
-- ----------------------------
INSERT INTO `provinces`(id, name, country_id) VALUES (1, 'ACEH', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (2, 'SUMATERA UTARA', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (3, 'SUMATERA BARAT', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (4, 'RIAU', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (5, 'JAMBI', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (6, 'SUMATERA SELATAN', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (7, 'BENGKULU', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (8, 'LAMPUNG', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (9, 'KEPULAUAN BANGKA BELITUNG', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (10, 'KEPULAUAN RIAU', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (11, 'DKI JAKARTA', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (12, 'JAWA BARAT', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (13, 'JAWA TENGAH', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (14, 'DI YOGYAKARTA', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (15, 'JAWA TIMUR', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (16, 'BANTEN', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (17, 'BALI', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (18, 'NUSA TENGGARA BARAT', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (19, 'NUSA TENGGARA TIMUR', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (20, 'KALIMANTAN BARAT', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (21, 'KALIMANTAN TENGAH', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (22, 'KALIMANTAN SELATAN', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (23, 'KALIMANTAN TIMUR', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (24, 'KALIMANTAN UTARA', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (25, 'SULAWESI UTARA', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (26, 'SULAWESI TENGAH', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (27, 'SULAWESI SELATAN', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (28, 'SULAWESI TENGGARA', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (29, 'GORONTALO', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (30, 'SULAWESI BARAT', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (31, 'MALUKU', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (32, 'MALUKU UTARA', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (33, 'PAPUA', 1);
INSERT INTO `provinces`(id, name, country_id) VALUES (34, 'PAPUA BARAT', 1);

-- ----------------------------
-- Table structure for cities
-- ----------------------------
-- DROP TABLE IF EXISTS `cities`;
-- CREATE TABLE `cities`  (
--   `city_id` int(11) NOT NULL AUTO_INCREMENT,
--   `city_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
--   `prov_id` int(11) NULL DEFAULT NULL,
--   PRIMARY KEY (`city_id`) USING BTREE
-- ) ENGINE = MyISAM AUTO_INCREMENT = 476 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of cities
-- ----------------------------
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (1, 'PIDIE JAYA', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (2, 'SIMEULUE', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (3, 'BIREUEN', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (4, 'ACEH TIMUR', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (5, 'ACEH UTARA', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (6, 'PIDIE', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (7, 'ACEH BARAT DAYA', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (8, 'GAYO LUES', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (9, 'ACEH SELATAN', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (10, 'ACEH TAMIANG', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (11, 'ACEH BESAR', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (12, 'ACEH TENGGARA', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (13, 'BENER MERIAH', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (14, 'ACEH JAYA', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (15, 'LHOKSEUMAWE', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (16, 'ACEH BARAT', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (17, 'NAGAN RAYA', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (18, 'LANGSA', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (19, 'BANDA ACEH', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (20, 'ACEH SINGKIL', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (21, 'SABANG', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (22, 'ACEH TENGAH', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (23, 'SUBULUSSALAM', 1, 1);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (24, 'NIAS SELATAN', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (25, 'MANDAILING NATAL', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (26, 'DAIRI', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (27, 'LABUHAN BATU UTARA', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (28, 'TAPANULI UTARA', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (29, 'SIMALUNGUN', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (30, 'LANGKAT', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (31, 'SERDANG BEDAGAI', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (32, 'TAPANULI SELATAN', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (33, 'ASAHAN', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (34, 'PADANG LAWAS UTARA', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (35, 'PADANG LAWAS', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (36, 'LABUHAN BATU SELATAN', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (37, 'PADANG SIDEMPUAN', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (38, 'TOBA SAMOSIR', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (39, 'TAPANULI TENGAH', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (40, 'HUMBANG HASUNDUTAN', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (41, 'SIBOLGA', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (42, 'BATU BARA', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (43, 'SAMOSIR', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (44, 'PEMATANG SIANTAR', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (45, 'LABUHAN BATU', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (46, 'DELI SERDANG', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (47, 'GUNUNGSITOLI', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (48, 'NIAS UTARA', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (49, 'NIAS', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (50, 'KARO', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (51, 'NIAS BARAT', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (52, 'MEDAN', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (53, 'PAKPAK BHARAT', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (54, 'TEBING TINGGI', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (55, 'BINJAI', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (56, 'TANJUNG BALAI', 1, 2);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (57, 'DHARMASRAYA', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (58, 'SOLOK SELATAN', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (59, 'SIJUNJUNG (SAWAH LUNTO SIJUNJUNG)', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (60, 'PASAMAN BARAT', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (61, 'SOLOK', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (62, 'PASAMAN', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (63, 'PARIAMAN', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (64, 'TANAH DATAR', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (65, 'PADANG PARIAMAN', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (66, 'PESISIR SELATAN', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (67, 'PADANG', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (68, 'SAWAH LUNTO', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (69, 'LIMA PULUH KOTO / KOTA', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (70, 'AGAM', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (71, 'PAYAKUMBUH', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (72, 'BUKITTINGGI', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (73, 'PADANG PANJANG', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (74, 'KEPULAUAN MENTAWAI', 1, 3);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (75, 'INDRAGIRI HILIR', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (76, 'KUANTAN SINGINGI', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (77, 'PELALAWAN', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (78, 'PEKANBARU', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (79, 'ROKAN HILIR', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (80, 'BENGKALIS', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (81, 'INDRAGIRI HULU', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (82, 'ROKAN HULU', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (83, 'KAMPAR', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (84, 'KEPULAUAN MERANTI', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (85, 'DUMAI', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (86, 'SIAK', 1, 4);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (87, 'TEBO', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (88, 'TANJUNG JABUNG BARAT', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (89, 'MUARO JAMBI', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (90, 'KERINCI', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (91, 'MERANGIN', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (92, 'BUNGO', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (93, 'TANJUNG JABUNG TIMUR', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (94, 'SUNGAIPENUH', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (95, 'BATANG HARI', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (96, 'JAMBI', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (97, 'SAROLANGUN', 1, 5);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (98, 'PALEMBANG', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (99, 'LAHAT', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (100, 'OGAN KOMERING ULU TIMUR', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (101, 'MUSI BANYUASIN', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (102, 'PAGAR ALAM', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (103, 'OGAN KOMERING ULU SELATAN', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (104, 'BANYUASIN', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (105, 'MUSI RAWAS', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (106, 'MUARA ENIM', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (107, 'OGAN KOMERING ULU', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (108, 'OGAN KOMERING ILIR', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (109, 'EMPAT LAWANG', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (110, 'LUBUK LINGGAU', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (111, 'PRABUMULIH', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (112, 'OGAN ILIR', 1, 6);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (113, 'BENGKULU TENGAH', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (114, 'REJANG LEBONG', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (115, 'MUKO MUKO', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (116, 'KAUR', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (117, 'BENGKULU UTARA', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (118, 'LEBONG', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (119, 'KEPAHIANG', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (120, 'BENGKULU SELATAN', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (121, 'SELUMA', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (122, 'BENGKULU', 1, 7);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (123, 'LAMPUNG UTARA', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (124, 'WAY KANAN', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (125, 'LAMPUNG TENGAH', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (126, 'MESUJI', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (127, 'PRINGSEWU', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (128, 'LAMPUNG TIMUR', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (129, 'LAMPUNG SELATAN', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (130, 'TULANG BAWANG', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (131, 'TULANG BAWANG BARAT', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (132, 'TANGGAMUS', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (133, 'LAMPUNG BARAT', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (134, 'PESISIR BARAT', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (135, 'PESAWARAN', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (136, 'BANDAR LAMPUNG', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (137, 'METRO', 1, 8);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (138, 'BELITUNG', 1, 9);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (139, 'BELITUNG TIMUR', 1, 9);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (140, 'BANGKA', 1, 9);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (141, 'BANGKA SELATAN', 1, 9);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (142, 'BANGKA BARAT', 1, 9);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (143, 'PANGKAL PINANG', 1, 9);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (144, 'BANGKA TENGAH', 1, 9);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (145, 'KEPULAUAN ANAMBAS', 1, 10);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (146, 'BINTAN', 1, 10);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (147, 'NATUNA', 1, 10);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (148, 'BATAM', 1, 10);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (149, 'TANJUNG PINANG', 1, 10);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (150, 'KARIMUN', 1, 10);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (151, 'LINGGA', 1, 10);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (152, 'JAKARTA UTARA', 1, 11);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (153, 'JAKARTA BARAT', 1, 11);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (154, 'JAKARTA TIMUR', 1, 11);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (155, 'JAKARTA SELATAN', 1, 11);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (156, 'JAKARTA PUSAT', 1, 11);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (157, 'KEPULAUAN SERIBU', 1, 11);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (158, 'DEPOK', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (159, 'KARAWANG', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (160, 'CIREBON', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (161, 'BANDUNG', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (162, 'SUKABUMI', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (163, 'SUMEDANG', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (164, 'INDRAMAYU', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (165, 'MAJALENGKA', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (166, 'KUNINGAN', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (167, 'TASIKMALAYA', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (168, 'CIAMIS', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (169, 'SUBANG', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (170, 'PURWAKARTA', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (171, 'BOGOR', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (172, 'BEKASI', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (173, 'GARUT', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (174, 'PANGANDARAN', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (175, 'CIANJUR', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (176, 'BANJAR', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (177, 'BANDUNG BARAT', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (178, 'CIMAHI', 1, 12);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (179, 'PURBALINGGA', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (180, 'KEBUMEN', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (181, 'MAGELANG', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (182, 'CILACAP', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (183, 'BATANG', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (184, 'BANJARNEGARA', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (185, 'BLORA', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (186, 'BREBES', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (187, 'BANYUMAS', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (188, 'WONOSOBO', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (189, 'TEGAL', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (190, 'PURWOREJO', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (191, 'PATI', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (192, 'SUKOHARJO', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (193, 'KARANGANYAR', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (194, 'PEKALONGAN', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (195, 'PEMALANG', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (196, 'BOYOLALI', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (197, 'GROBOGAN', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (198, 'SEMARANG', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (199, 'DEMAK', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (200, 'REMBANG', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (201, 'KLATEN', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (202, 'KUDUS', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (203, 'TEMANGGUNG', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (204, 'SRAGEN', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (205, 'JEPARA', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (206, 'WONOGIRI', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (207, 'KENDAL', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (208, 'SURAKARTA', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (209, 'SALATIGA', 1, 13);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (210, 'SLEMAN', 1, 14);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (211, 'BANTUL', 1, 14);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (212, 'YOGYAKARTA', 1, 14);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (213, 'GUNUNG KIDUL', 1, 14);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (214, 'KULON PROGO', 1, 14);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (215, 'GRESIK', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (216, 'KEDIRI', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (217, 'SAMPANG', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (218, 'BANGKALAN', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (219, 'SUMENEP', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (220, 'SITUBONDO', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (221, 'SURABAYA', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (222, 'JEMBER', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (223, 'PAMEKASAN', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (224, 'JOMBANG', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (225, 'PROBOLINGGO', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (226, 'BANYUWANGI', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (227, 'PASURUAN', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (228, 'BOJONEGORO', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (229, 'BONDOWOSO', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (230, 'MAGETAN', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (231, 'LUMAJANG', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (232, 'MALANG', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (233, 'BLITAR', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (234, 'SIDOARJO', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (235, 'LAMONGAN', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (236, 'PACITAN', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (237, 'TULUNGAGUNG', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (238, 'MOJOKERTO', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (239, 'MADIUN', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (240, 'PONOROGO', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (241, 'NGAWI', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (242, 'NGANJUK', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (243, 'TUBAN', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (244, 'TRENGGALEK', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (245, 'BATU', 1, 15);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (246, 'TANGERANG', 1, 16);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (247, 'SERANG', 1, 16);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (248, 'PANDEGLANG', 1, 16);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (249, 'LEBAK', 1, 16);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (250, 'TANGERANG SELATAN', 1, 16);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (251, 'CILEGON', 1, 16);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (252, 'KLUNGKUNG', 1, 17);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (253, 'KARANGASEM', 1, 17);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (254, 'BANGLI', 1, 17);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (255, 'TABANAN', 1, 17);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (256, 'GIANYAR', 1, 17);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (257, 'BADUNG', 1, 17);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (258, 'JEMBRANA', 1, 17);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (259, 'BULELENG', 1, 17);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (260, 'DENPASAR', 1, 17);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (261, 'MATARAM', 1, 18);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (262, 'DOMPU', 1, 18);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (263, 'SUMBAWA BARAT', 1, 18);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (264, 'SUMBAWA', 1, 18);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (265, 'LOMBOK TENGAH', 1, 18);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (266, 'LOMBOK TIMUR', 1, 18);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (267, 'LOMBOK UTARA', 1, 18);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (268, 'LOMBOK BARAT', 1, 18);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (269, 'BIMA', 1, 18);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (270, 'TIMOR TENGAH SELATAN', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (271, 'FLORES TIMUR', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (272, 'ALOR', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (273, 'ENDE', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (274, 'NAGEKEO', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (275, 'KUPANG', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (276, 'SIKKA', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (277, 'NGADA', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (278, 'TIMOR TENGAH UTARA', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (279, 'BELU', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (280, 'LEMBATA', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (281, 'SUMBA BARAT DAYA', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (282, 'SUMBA BARAT', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (283, 'SUMBA TENGAH', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (284, 'SUMBA TIMUR', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (285, 'ROTE NDAO', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (286, 'MANGGARAI TIMUR', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (287, 'MANGGARAI', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (288, 'SABU RAIJUA', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (289, 'MANGGARAI BARAT', 1, 19);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (290, 'LANDAK', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (291, 'KETAPANG', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (292, 'SINTANG', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (293, 'KUBU RAYA', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (294, 'PONTIANAK', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (295, 'KAYONG UTARA', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (296, 'BENGKAYANG', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (297, 'KAPUAS HULU', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (298, 'SAMBAS', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (299, 'SINGKAWANG', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (300, 'SANGGAU', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (301, 'MELAWI', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (302, 'SEKADAU', 1, 20);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (303, 'KOTAWARINGIN TIMUR', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (304, 'SUKAMARA', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (305, 'KOTAWARINGIN BARAT', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (306, 'BARITO TIMUR', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (307, 'KAPUAS', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (308, 'PULANG PISAU', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (309, 'LAMANDAU', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (310, 'SERUYAN', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (311, 'KATINGAN', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (312, 'BARITO SELATAN', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (313, 'MURUNG RAYA', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (314, 'BARITO UTARA', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (315, 'GUNUNG MAS', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (316, 'PALANGKA RAYA', 1, 21);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (317, 'TAPIN', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (318, 'BANJAR', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (319, 'HULU SUNGAI TENGAH', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (320, 'TABALONG', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (321, 'HULU SUNGAI UTARA', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (322, 'BALANGAN', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (323, 'TANAH BUMBU', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (324, 'BANJARMASIN', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (325, 'KOTABARU', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (326, 'TANAH LAUT', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (327, 'HULU SUNGAI SELATAN', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (328, 'BARITO KUALA', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (329, 'BANJARBARU', 1, 22);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (330, 'KUTAI BARAT', 1, 23);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (331, 'SAMARINDA', 1, 23);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (332, 'PASER', 1, 23);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (333, 'KUTAI KARTANEGARA', 1, 23);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (334, 'BERAU', 1, 23);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (335, 'PENAJAM PASER UTARA', 1, 23);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (336, 'BONTANG', 1, 23);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (337, 'KUTAI TIMUR', 1, 23);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (338, 'BALIKPAPAN', 1, 23);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (339, 'MALINAU', 1, 24);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (340, 'NUNUKAN', 1, 24);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (341, 'BULUNGAN (BULONGAN)', 1, 24);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (342, 'TANA TIDUNG', 1, 24);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (343, 'TARAKAN', 1, 24);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (344, 'BOLAANG MONGONDOW (BOLMONG)', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (345, 'BOLAANG MONGONDOW SELATAN', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (346, 'MINAHASA SELATAN', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (347, 'BITUNG', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (348, 'MINAHASA', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (349, 'KEPULAUAN SANGIHE', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (350, 'MINAHASA UTARA', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (351, 'KEPULAUAN TALAUD', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (352, 'KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (353, 'MANADO', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (354, 'BOLAANG MONGONDOW UTARA', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (355, 'BOLAANG MONGONDOW TIMUR', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (356, 'MINAHASA TENGGARA', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (357, 'KOTAMOBAGU', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (358, 'TOMOHON', 1, 25);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (359, 'BANGGAI KEPULAUAN', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (360, 'TOLI-TOLI', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (361, 'PARIGI MOUTONG', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (362, 'BUOL', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (363, 'DONGGALA', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (364, 'POSO', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (365, 'MOROWALI', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (366, 'TOJO UNA-UNA', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (367, 'BANGGAI', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (368, 'SIGI', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (369, 'PALU', 1, 26);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (370, 'MAROS', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (371, 'WAJO', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (372, 'BONE', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (373, 'SOPPENG', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (374, 'SIDENRENG RAPPANG / RAPANG', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (375, 'TAKALAR', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (376, 'BARRU', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (377, 'LUWU TIMUR', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (378, 'SINJAI', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (379, 'PANGKAJENE KEPULAUAN', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (380, 'PINRANG', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (381, 'JENEPONTO', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (382, 'PALOPO', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (383, 'TORAJA UTARA', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (384, 'LUWU', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (385, 'BULUKUMBA', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (386, 'MAKASSAR', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (387, 'SELAYAR (KEPULAUAN SELAYAR)', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (388, 'TANA TORAJA', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (389, 'LUWU UTARA', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (390, 'BANTAENG', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (391, 'GOWA', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (392, 'ENREKANG', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (393, 'PAREPARE', 1, 27);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (394, 'KOLAKA', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (395, 'MUNA', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (396, 'KONAWE SELATAN', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (397, 'KENDARI', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (398, 'KONAWE', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (399, 'KONAWE UTARA', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (400, 'KOLAKA UTARA', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (401, 'BUTON', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (402, 'BOMBANA', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (403, 'WAKATOBI', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (404, 'BAU-BAU', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (405, 'BUTON UTARA', 1, 28);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (406, 'GORONTALO UTARA', 1, 29);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (407, 'BONE BOLANGO', 1, 29);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (408, 'GORONTALO', 1, 29);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (409, 'BOALEMO', 1, 29);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (410, 'POHUWATO', 1, 29);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (411, 'MAJENE', 1, 30);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (412, 'MAMUJU', 1, 30);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (413, 'MAMUJU UTARA', 1, 30);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (414, 'POLEWALI MANDAR', 1, 30);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (415, 'MAMASA', 1, 30);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (416, 'MALUKU TENGGARA BARAT', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (417, 'MALUKU TENGGARA', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (418, 'SERAM BAGIAN BARAT', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (419, 'MALUKU TENGAH', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (420, 'SERAM BAGIAN TIMUR', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (421, 'MALUKU BARAT DAYA', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (422, 'AMBON', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (423, 'BURU', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (424, 'BURU SELATAN', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (425, 'KEPULAUAN ARU', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (426, 'TUAL', 1, 31);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (427, 'HALMAHERA BARAT', 1, 32);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (428, 'TIDORE KEPULAUAN', 1, 32);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (429, 'TERNATE', 1, 32);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (430, 'PULAU MOROTAI', 1, 32);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (431, 'KEPULAUAN SULA', 1, 32);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (432, 'HALMAHERA SELATAN', 1, 32);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (433, 'HALMAHERA TENGAH', 1, 32);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (434, 'HALMAHERA TIMUR', 1, 32);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (435, 'HALMAHERA UTARA', 1, 32);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (436, 'YALIMO', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (437, 'DOGIYAI', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (438, 'ASMAT', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (439, 'JAYAPURA', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (440, 'PANIAI', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (441, 'MAPPI', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (442, 'TOLIKARA', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (443, 'PUNCAK JAYA', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (444, 'PEGUNUNGAN BINTANG', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (445, 'JAYAWIJAYA', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (446, 'LANNY JAYA', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (447, 'NDUGA', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (448, 'BIAK NUMFOR', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (449, 'KEPULAUAN YAPEN (YAPEN WAROPEN)', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (450, 'PUNCAK', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (451, 'INTAN JAYA', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (452, 'WAROPEN', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (453, 'NABIRE', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (454, 'MIMIKA', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (455, 'BOVEN DIGOEL', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (456, 'YAHUKIMO', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (457, 'SARMI', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (458, 'MERAUKE', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (459, 'DEIYAI (DELIYAI)', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (460, 'KEEROM', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (461, 'SUPIORI', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (462, 'MAMBERAMO RAYA', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (463, 'MAMBERAMO TENGAH', 1, 33);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (464, 'RAJA AMPAT', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (465, 'MANOKWARI SELATAN', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (466, 'MANOKWARI', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (467, 'KAIMANA', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (468, 'MAYBRAT', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (469, 'SORONG SELATAN', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (470, 'FAKFAK', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (471, 'PEGUNUNGAN ARFAK', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (472, 'TAMBRAUW', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (473, 'SORONG', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (474, 'TELUK WONDAMA', 1, 34);
INSERT INTO `cities`(id, name, country_id, province_id) VALUES (475, 'TELUK BINTUNI', 1, 34);

SET FOREIGN_KEY_CHECKS = 1;
